### ISSUE TITLE
bugfix:日志等级

### ISSUE THREAD

**Issue by cbluebird** [SugarMGP/ConfessionWallServer#1]
日志等级处理的有点混乱，
INFO处理的是系统的一些信息，比如server start ，mysql init 这些，而不应该是zap.L().Info("创建拉黑成功", zap.Uint("user_id", id), zap.Uint("target_id", post.User))这种类型
ERROR是指出虽然发生错误事件，但仍然不影响系统的继续运行。打印错误和异常信息，如果不想输出太多的日志，可以使用这个级别。zap.L().Error("查询拉黑信息失败", zap.Uint("user_id", id), zap.Uint("target_id", post.User), zap.Error(err))

上述两种放在debug中更为合适

关于决定使用哪种mod，放在flag中去解析感觉更为稳妥，这不算是系统的参数🤔

**Comment by SugarMGP** [comment]
其实日志输出已经削了一次了，你见到的那些debug一开始都是error（
关于现在的info我想的是对用户的操作进行一个记录，error则是出于"可以被预测的错误使用debug，其余用error"的原则写的。
当然你的建议不无道理，我们组会再讨论讨论

**Comment by SugarMGP** [comment]
补充："不能被预测的错误"对应InternalServerError响应

**Comment by cbluebird** [comment]
> 补充："不能被预测的错误"对应InternalServerError响应

这个可以尝试用中间件去收集，可以不用在单独写出。

INFO是比较重要的信息，不应该放这些记录，他相当于是一个系统状态的查看，有时候我们可能会启动携程去收集一些系统相关的INFO，所以不应该zap.L().Info("创建拉黑成功", zap.Uint("user_id", id), zap.Uint("target_id", post.User))这种与系统本身状态相关的占用。其次这些日志都是可以从mysql的日志中收集到的

**Comment by SugarMGP** [comment]
好滴我知道了，话说有没有例子给我参考一下（

**Comment by SugarMGP** [comment]
> > 补充："不能被预测的错误"对应InternalServerError响应
> 
> 这个可以尝试用中间件去收集，可以不用在单独写出。
> 
> INFO是比较重要的信息，不应该放这些记录，他相当于是一个系统状态的查看，有时候我们可能会启动携程去收集一些系统相关的INFO，所以不应该zap.L().Info("创建拉黑成功", zap.Uint("user_id", id), zap.Uint("target_id", post.User))这种与系统本身状态相关的占用。其次这些日志都是可以从mysql的日志中收集到的

好滴我知道了，话说有没有例子给我参考一下（
